Update messages.po
cryptoadvance/specter-desktop pull request #1273
Opened 2021-07-06 19:31 UTC by Sh0ham

2021-07-06 20:18 UTC, ben-kaufman requested changes
Looks good! I added a few comments on typos and suggestions for improvement

2021-07-06 20:18 UTC, ben-kaufman commented on src/cryptoadvance/specter/translations/he/LC_MESSAGES/messages.po
> +msgstr "הוסף לתחום"
I think הוסף את הכתובת would be better in the context of this

2021-07-06 20:18 UTC, ben-kaufman commented on src/cryptoadvance/specter/translations/he/LC_MESSAGES/messages.po
> +msgstr "אפשר גישה לספקטר מכל מקום."
אפשר -> מאפשר

2021-07-06 20:18 UTC, ben-kaufman commented on src/cryptoadvance/specter/translations/he/LC_MESSAGES/messages.po
> +msgstr "יחידה מידע:"
typo should be : יחידת מידה

2021-07-06 20:18 UTC, ben-kaufman commented on src/cryptoadvance/specter/translations/he/LC_MESSAGES/messages.po
> +msgstr "חשב הערכת עמלה"
חשב עמלה משוערת

Might be better here

2021-07-07 05:31 UTC, Sh0ham commented on src/cryptoadvance/specter/translations/he/LC_MESSAGES/messages.po
> +msgstr "ברירת הממחדל לשם משתמש הוא 'admin', ולסיסממה 'admin'"
Fucking MacBook butterfly keyboard :(

2021-07-09 14:36 UTC, ben-kaufman commented on src/cryptoadvance/specter/translations/he/LC_MESSAGES/messages.po
> +msgstr "זמןמ"
Still not resolved?

2021-07-09 14:36 UTC, ben-kaufman commented
Comments still don't seem to be resolved... Also need to run:
pybabel update -N --no-wrap -i babel/messages.pot -d src/cryptoadvance/specter/translations -l he

2021-07-10 16:06 UTC, closed without merging