Docs: Release guide
cryptoadvance/specter-desktop pull request #1930
Opened 2022-10-17 18:24 UTC by moneymanolis

This adds a release guide to help remembering all the necessary steps, especially since not everything is / can be automated.

2022-10-18 14:32 UTC, k9ert commented on docs/release-guide.md
> +```
```suggestion
```bash 
git remote -v | grep upstream                                                                  
upstream        git@github.com:cryptoadvance/specter-desktop.git (fetch)
upstream        git@github.com:cryptoadvance/specter-desktop.git (push)
```
```

2022-10-18 14:33 UTC, k9ert commented on docs/release-guide.md
> +### Creating release notes
```suggestion
# Release Guide

## Creating release notes
```

2022-10-18 14:34 UTC, k9ert commented on docs/release-guide.md
> +```
docker as a prerequisite is missing, no?!

2022-10-18 14:35 UTC, k9ert commented on docs/release-guide.md
> +specter_desktop-v1.13.1-x86_64-linux-gnu.tar.gz
```suggestion
- cryptoadvance.specter-1.13.1.tar.gz
- Specter-Setup-v1.13.1.exe
- specterd-v1.13.1-win64.zip
- specterd-v1.13.1-x86_64-linux-gnu.zip
- specter_desktop-v1.13.1-x86_64-linux-gnu.tar.gz
```

2022-10-18 14:36 UTC, k9ert commented on docs/release-guide.md
> +release_pip: Is releasing a pypi package on [pypi](https://pypi.org/project/cryptoadvance.specter/) and creates a tarball of the pip package for the GitHub release page (Linux runner).
```suggestion
- release_binary_windows: is creating a binary for specterd and for Windows (Windows runner)
- release_electron_linux_windows: Creates a specterd for Linux, an AppImage for Linux and an executable for Windows (Linux runner).
- release_pip: Is releasing a pypi package on [pypi](https://pypi.org/project/cryptoadvance.specter/) and creates a tarball of the pip package for the GitHub release page (Linux runner). 
```

2022-10-18 14:40 UTC, k9ert commented on docs/release-guide.md
> +SHA256SUMS.asc
```suggestion
- SHA256SUMS
- SHA256SUMS.asc
```

2022-10-18 14:41 UTC, k9ert commented on docs/release-guide.md
> +`download-page_releases.html`
```suggestion
- `download-page_current.html`
- `download-page_releases.html`
```

2022-10-18 14:42 UTC, k9ert requested changes
Some recommended changes ...

2022-10-18 18:53 UTC, moneymanolis commented
All requests should have been addressed.

2022-10-19 08:01 UTC, k9ert approved these changes

2022-10-19 08:01 UTC, merged