fixed tooltip not overlaying
cryptoadvance/specter-desktop pull request #2116
Opened 2023-01-31 23:00 UTC by PaarthAgarwal

Fixes #2113.
The issue arose because of the opacity property in .button:hover. I've replaced opacity with rgba while keeping UI the same as before. 
Before the fix
![Screenshot from 2023-02-01 04-29-29](https://user-images.githubusercontent.com/86092410/215903278-4a2df9fd-43b0-471c-a917-a4185824c6bf.png)

After the fix
![Screenshot from 2023-02-01 04-25-30](https://user-images.githubusercontent.com/86092410/215902826-e55a42c2-ccf6-47c7-b31a-3c5d8477f4fc.png)

2023-02-01 14:28 UTC, moneymanolis requested changes
Has to be resolved differently.

2023-02-01 14:52 UTC, moneymanolis commented on src/cryptoadvance/specter/static/style.css
> +    @apply h-11 rounded-xl text-lg flex items-center space-x-2 justify-center bg-dark-600 hover:opacity-80 px-10 cursor-pointer w-[calc(688px/2)] mb-3 z-10;
For some reason, `z-0` doesn't work.

2023-02-01 14:53 UTC, moneymanolis commented
@otkstdio I made an attempt in https://github.com/cryptoadvance/specter-desktop/pull/2116/commits/c3fa48455b0ec13d6aa75bd39c5275d353dbba81, let me know what you think about it.

2023-02-07 14:07 UTC, otkstdio commented
> 

Did the attempt work?

2023-02-08 10:24 UTC, moneymanolis commented
@otkstdio I've rebuilt the `output.css `- now it's fine, merging ... @PaarthAgarwal thanks, please keep in my mind for the next PRs to not change the output.css directly. See also comment above.

2023-02-10 10:00 UTC, PaarthAgarwal commented
> @otkstdio I've rebuilt the `output.css `- now it's fine, merging once the tests are green. @PaarthAgarwal thanks, please keep in my mind for the next PRs to not change the output.css directly. See also comment above.

If I make changes in style.css will they be automatically reflected in output.css? If not then how to build output.css again from style.css?

2023-02-13 08:23 UTC, moneymanolis approved these changes

2023-02-13 08:47 UTC, PaarthAgarwal commented
> @PaarthAgarwal You need to run `npm run tailwind` for the building of `output.css`. @otkstdio we need to put all this in the developer documentation for the front end.

Oh I see
Should I open a PR to add this in docs?

2023-02-13 09:57 UTC, merged