More consistent tor-setup
cryptoadvance/specter-desktop pull request #2234
Opened 2023-02-20 14:34 UTC by k9ert

2023-02-20 15:05 UTC, k9ert commented
* There was never an option to not use tor but at the same time it not has been properly setup from the start. So now we have three possible values for `tor_type`: `none`, `builtin` or `custom`. 
* `builtin` is now no longer chooseable in the setup screen if you use a pip-installation
* A bit better error-handling which should prevent that an issue like this blocks proper startup (from the chat):
```
  File "/home/specter/.local/lib/python3.9/site-packages/stem/connection.py", line 1107, in _read_cookie
    raise UnreadableCookieFile(exc_msg, cookie_path, is_safecookie)
stem.connection.UnreadableCookieFile: Authentication failed: unable to read '/run/tor/control.authcookie' ([Errno 13] Permission denied: '/run/tor/control.authcookie')
```

2023-02-20 15:18 UTC, moneymanolis commented on docs/architecture.md
> +Tor support is possible either via a custom installation or via the built in. The type of the installation is stored in `specter.tor_type` which is redirecting to the `config_manager` which by defaul
```suggestion
Tor support is possible either via a custom or via the built-in installation. The type of installation is stored in `specter.tor_type` which is redirecting to the `config_manager` which by default returns `builtin`. Another valid value is `custom` and initially we have `none`.
```

2023-02-20 15:25 UTC, moneymanolis commented on src/cryptoadvance/specter/server_endpoints/settings.py
> +    tor_builtin_possible = getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS")
Comment would be nice! Sth. like
```suggestion
    # This is true if the Python interpreter has been bundled with the application into a single executable, so basically it is true for the apps but not for pip-installations
    tor_builtin_possible = getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS")
```

2023-02-20 18:02 UTC, moneymanolis commented
Shouldn't there be check whether the tor_controller attr exists like so:
```
    @property
    def tor_controller(self):
        if hasattr(self, "_tor_controller") and self._tor_controller:
            return self._tor_controller
        self.update_tor_controller()
        if hasattr(self, "_tor_controller") and self._tor_controller:
            return self._tor_controller
        raise SpecterError(
            "Failed to connect to the Tor daemon. Make sure ControlPort is properly configured."
        )
```

Without it, I get this when closing Specter:

```
...

 if app.specter.tor_controller is not None:
  File "/Users/heinzi/coding/repos/specter-desktop/src/cryptoadvance/specter/specter.py", line 453, in tor_controller
    if self._tor_controller:
AttributeError: 'Specter' object has no attribute '_tor_controller'. Did you mean: 'tor_control_port'?
```

2023-02-20 18:03 UTC, moneymanolis commented
Slight change in UI in https://github.com/cryptoadvance/specter-desktop/pull/2234/commits/dafe308f023d7b5626e86774c8180205d76e20c8:
![grafik](https://user-images.githubusercontent.com/70536101/220175030-6633c253-48d2-4960-9da4-7f9649ffce26.png)

2023-02-20 18:04 UTC, moneymanolis requested changes
Some small suggestions and one question.

2023-02-21 13:15 UTC, k9ert commented
> Without it, I get this when closing Specter:

Absolutely. Changed it with [8a9b355](https://github.com/cryptoadvance/specter-desktop/pull/2234/commits/8a9b35501537e2ea3f47e1fea2359edc7358a6a1)

2023-02-21 13:46 UTC, moneymanolis approved these changes

2023-02-21 17:24 UTC, merged