Apply copy improvements & Electrum UX cleanup
cryptoadvance/specter-desktop pull request #2237
Opened 2023-02-20 22:16 UTC by otkstdio

This improves the electrum connection UX and other copy changes throughout the app

2023-02-21 10:30 UTC, k9ert commented on src/cryptoadvance/specter/templates/includes/sidebar/sidebar.jinja
> +                    <svg class="fill-current" width="20" height="20" version="1.1" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><!--Generated by I
Can we put that to an extra-file?

2023-02-21 17:01 UTC, k9ert commented on src/cryptoadvance/specter/templates/includes/sidebar/sidebar.jinja
> +                    <svg class="fill-current" width="20" height="20" version="1.1" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><!--Generated by I
Ok, let's do it at some other time. Can you create an issue for that?

2023-02-21 17:01 UTC, k9ert approved these changes

2023-02-21 17:20 UTC, moneymanolis requested changes
When you take out the selection that Spectrum is shown in the menu, you can not set this option so it won't show in the sidebar. 
Either keep this selection option or set to be shown in the sidebar after connecting successfully for the first time. 

Also see suggestion comment.

2023-02-21 17:54 UTC, otkstdio commented
@moneymanolis we decided to not show the plugin on the sidebar at all as the paradigm for the user is to think of it as a type of connection. It can be managed by clicking into the connection details top left of the sidebar and then select settings on the connection. Instead of having two methods and two paradigms for accessing it.

I'm fixing the icon selection now with a coming commit.

2023-02-21 18:00 UTC, moneymanolis commented
> @moneymanolis we decided to not show the plugin on the sidebar at all as the paradigm for the user is to think of it as a type of connection. It can be managed by clicking into the connection details top left of the sidebar and then select settings on the connection. Instead of having two methods and two paradigms for accessing it.
> 
> I'm fixing the icon selection now with a coming commit.

OK, fine by me!

2023-02-22 07:47 UTC, moneymanolis commented
I can still hardly see the favicon (too small) and I think the ghost should be white:

<img width="491" alt="grafik" src="https://user-images.githubusercontent.com/70536101/220555636-ad8db93d-4641-4569-942a-fabe24b48eb8.png">

2023-02-22 18:16 UTC, moneymanolis approved these changes

2023-02-22 18:25 UTC, merged