Fixes issue #1957
cryptoadvance/specter-desktop pull request #2252
Opened 2023-02-23 18:10 UTC by Aditi-Singh16

2023-02-24 13:32 UTC, k9ert commented
Great! However, the test is failing. You have to adjust it as you changed the constructor.

2023-02-27 08:36 UTC, k9ert commented on src/cryptoadvance/specter/services/extension_gen.py
> +            if vc._check_if_version_is_available(custom_version) == True:
`== True` is not needed. In order to improve readability, you could rename the method and call it:
```suggestion
            if vc._version_is_available(custom_version):
```
Comparing methods which return booleans explicitely is a common issue. It's not wrong but i hope the readability improvement above makes sense to you.

2023-02-27 08:47 UTC, k9ert commented on src/cryptoadvance/specter/services/extension_gen.py
> +        if self.custom_version != "":
Please have a look how `branch` and `version` is used. the feature i mostly spoke about was using specific branches (tags) as the basis for the templating [here](https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/services/extension_gen.py#L66).
Yes, the `self.version` is used for specific templates in order to render out the version this extension is dependent on. But the branch variable specifies which templates are used: [branches (or tags, doesn't matter) in the specterext-dummy-repo](https://github.com/cryptoadvance/specterext-dummy/tags). You can rename "branch" to "tag" which would make more sense.

2023-02-27 08:49 UTC, k9ert commented on src/cryptoadvance/specter/cli/cli_ext.py
> +            The extension generation uses the latest version of specter.
I think a fallback should rather be not the lastest version, but the version ext_gen is running on. That can be found (in <= v2) in `from cryptoadvance.specter._version import version`.

2023-02-27 08:50 UTC, k9ert commented on src/cryptoadvance/specter/util/version.py
> +        checks if version requested is available or not.
```suggestion
        checks if that version is available as a package on pypi.
```

2023-02-27 08:53 UTC, k9ert commented
Looks You haven't addressed the test yet. Please run the tests and fix them. If you click on "details" and then on "Raw output", you see the reason why the test is failing:
```
caplog = <_pytest.logging.LogCaptureFixture object at 0x7f4b0a34fdf0>

    def test_ExtGen(caplog):
    
        with patch("cryptoadvance.specter.services.extension_gen.GithubUrlLoader") as mock:
>           extgen = ExtGen(
                ".",
                "testorg",
                "testext",
                False,
                False,
                "Some Author",
                "some@mail",
                # uncomment the below line to see a real generation
                # tmpl_fs_source="../specterext-dummy",
                dry_run=True,
            )
E           TypeError: ExtGen.__init__() missing 2 required positional arguments: 'author' and 'email'

tests/test_services_extension_gen.py:14: TypeError
```

2023-02-27 08:53 UTC, k9ert requested changes
see the above comments

2023-02-27 11:28 UTC, k9ert commented
BTW, most important from all: This PR is going to master but should go to uiux-revamp branch.

2023-02-27 17:03 UTC, k9ert commented
Sorry, we have moved the uiux-revamp branch to the master branch which now results with a lot of conflicts. So this PR needs to be recreated. Please do something like this:
```
git checkout master
git pull upstream master
git checkout -b ext-update-new
git cherry-pick 5814c687dd555e92fc7315c1749eb4fa9acf510a 1c7436b51a14794ffc637dab41bbcaf71e86ff1c cc706a0b7e20681ed6cec9b8549ae106e1e2e3a7 fc831ba86ea93d22b2328eeaaa45cfd5be2c5f4c
git commit
git push
```

And then please recreate the PR.

2023-02-28 18:46 UTC, Aditi-Singh16 commented
Okay sure!

2023-02-28 18:46 UTC, closed without merging